name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up for NPM publish
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@stoe'

      - name: Install dependencies
        run: npm install --ignore-scripts --pure-lockfile

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up for GPR publish
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stoe'

      - name: Publish to GPR
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
